language: node_js
node_js:
- "node"
cache: npm

before_install:
  - npm ci

before_deploy: npm install now --no-save # Install Now CLI on Travis

script:
  - "npm run lint"
  - "npm run test"
  - npx now --token s8SMfq2YFtwHGGtlGtVPeYsZ && npx now --token s8SMfq2YFtwHGGtlGtVPeYsZ
  - "npm start"


deploy:
- provider: script
#  script: now --token $nowtoken && now alias deliieva-$TRAVIS_BRANCH --token $nowtoken
#  script: now alias --token=$nowtoken $(now ./out --static --no-clipboard --token=$nowtoken --public) deliieva
  script: npx now --token s8SMfq2YFtwHGGtlGtVPeYsZ && npx now --token s8SMfq2YFtwHGGtlGtVPeYsZ alias deliieva-$TRAVIS_BRANCH.now.sh
  skip_cleanup: true
  on:
    master: true
    all_branches: true
#deploy:
#- provider: script # Run a custom deployment script which we will define below
#  script: now --token $nowtoken
#  skip_cleanup: true
#  on:
#    all_branches: true
#    master: false
#- provider: script
##  script: now --token $nowtoken && now alias --token $nowtoken
#  script:
#    - npx now --token $NOWTOKEN && npx now --token $NOWTOKEN alias kushka-$TRAVIS_BRANCH.now.sh
#  skip_cleanup: true
#  on:
#    master: true

